In [5]:
import pandas as pd

#creat from a csv
df=pd.read_csv('ai4i2020.csv')

print(df.head() )#return top 5 rows
df.tail() #return bottom 5 rows
#creat from a dictionary
tempdic={'col1':[1,2,3],'col2':[4,5,6],'col3':[7,8,9]}
dictdf=pd.DataFrame.from_dict(tempdic)
dictdf

   UDI Product ID Type  Air temperature [K]  ...  HDF  PWF  OSF  RNF
0    1     M14860    M                298.1  ...    0    0    0    0
1    2     L47181    L                298.2  ...    0    0    0    0
2    3     L47182    L                298.1  ...    0    0    0    0
3    4     L47183    L                298.2  ...    0    0    0    0
4    5     L47184    L                298.2  ...    0    0    0    0

[5 rows x 14 columns]

   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6     9

In [11]:
#show column and data type
#print(df.columns)
#print(df.dtypes)
#summary statistics
df.describe()
df.describe(include='object')

       Product ID   Type
count       10000  10000
unique      10000      3
top        M14904      L
freq            1   6000

In [14]:
#filtering columns
#print(df.Type)
#print(df[['Product ID','Type']])
df.Type.unique()

array(['M', 'L', 'H'], dtype=object)

In [17]:
#filtering on rows
df[df['Type']=='M']
df[df['Air temperature [K]']==298.1]
df[(df['Air temperature [K]']==298.1) & (df['Type']=='M')]

       UDI Product ID Type  Air temperature [K]  ...  HDF  PWF  OSF  RNF
0        1     M14860    M                298.1  ...    0    0    0    0
5        6     M14865    M                298.1  ...    0    0    0    0
172    173     M15032    M                298.1  ...    0    0    0    0
182    183     M15042    M                298.1  ...    0    0    0    0
235    236     M15095    M                298.1  ...    0    0    0    0
...    ...        ...  ...                  ...  ...  ...  ...  ...  ...
9442  9443     M24302    M                298.1  ...    0    0    0    0
9447  9448     M24307    M                298.1  ...    0    0    0    0
9449  9450     M24309    M                298.1  ...    0    0    0    0
9954  9955     M24814    M                298.1  ...    0    0    0    0
9958  9959     M24818    M                298.1  ...    0    0    0    0

[78 rows x 14 columns]

In [21]:
#indexing with iloc
df.iloc[5] # return 5-th row

df.iloc[5,1]# return index 1 of cloumn from row 5
df.iloc[5,-1]
df.iloc[25:38]

    UDI Product ID Type  Air temperature [K]  ...  HDF  PWF  OSF  RNF
25   26     L47205    L                299.0  ...    0    0    0    0
26   27     L47206    L                299.1  ...    0    0    0    0
27   28     H29441    H                299.1  ...    0    0    0    0
28   29     L47208    L                299.1  ...    0    0    0    0
29   30     L47209    L                299.0  ...    0    0    0    0
30   31     M14890    M                299.1  ...    0    0    0    0
31   32     L47211    L                299.0  ...    0    0    0    0
32   33     L47212    L                299.0  ...    0    0    0    0
33   34     L47213    L                298.9  ...    0    0    0    0
34   35     M14894    M                298.8  ...    0    0    0    0
35   36     M14895    M                298.8  ...    0    0    0    0
36   37     M14896    M                298.9  ...    0    0    0    0
37   38     L47217    L                298.8  ...    0    0    0    0

[13 rows x 14 columns]

In [23]:
#indexing with loc
state=df.copy()
state.set_index('Type',inplace=True)
state.head()
state.loc['M'] #indexing with non integer

        UDI Product ID  Air temperature [K]  ...  PWF  OSF  RNF
Type                                         ...
M         1     M14860                298.1  ...    0    0    0
M         6     M14865                298.1  ...    0    0    0
M         9     M14868                298.3  ...    0    0    0
M        10     M14869                298.5  ...    0    0    0
M        13     M14872                298.6  ...    0    0    0
...     ...        ...                  ...  ...  ...  ...  ...
M      9990     M24849                298.8  ...    0    0    0
M      9992     M24851                298.9  ...    0    0    0
M      9996     M24855                298.8  ...    0    0    0
M      9998     M24857                299.0  ...    0    0    0
M     10000     M24859                299.0  ...    0    0    0

[2997 rows x 13 columns]

In [30]:
df.isnull().sum()
df['new col']=df['Air temperature [K]']+df['Process temperature [K]']
df['new col']=150
df.iloc[1,-1]=100
df.loc[0:200,'Type']='M'
df.loc[200:df.size,'Type']='N'
df['binary type']=df['Type'].apply(lambda x: 1 if x=='M' else 0)
df.tail()

        UDI Product ID Type  ...  RNF  new col  binary type
9995   9996     M24855    N  ...    0      150            0
9996   9997     H39410    N  ...    0      150            0
9997   9998     M24857    N  ...    0      150            0
9998   9999     H39412    N  ...    0      150            0
9999  10000     M24859    N  ...    0      150            0

[5 rows x 16 columns]

In [ ]:
#dropping rows
df.isnull().sum()
df.dropna(inplace=True)
#droping column
df.drop('Type',axis=1)
#creating clculated columns
df['new col']=df['Air temperature [K]']+df['Process temperature [K]']
#updating an entire col
df['new col']=150
#updating single value 
df.iloc[1,-1]=100
#condition based updating using apply
df.loc[0:200,'Type']='M'
df.loc[200:df.size,'Type']='N'
df['binary type']=df['Type'].apply(lambda x: 1 if x=='M' else 0)
df[df['Type']=='M'].tail()

# output csv
df.to_csv('output.csv')